[webservers]
webserver-1 ansible_host=10.0.10.240 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa
webserver-2 ansible_host=10.0.11.200 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa

[database]
database-1 ansible_host=10.0.20.225 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa


